---
java:
  disable:
    - FileTabCharacter
    - LineLength  
    - MethodName
    
checkstyle:
  disable:
    - HideUtilityClassConstructor
    - VisibilityModifier
    - DesignForExtension
    - FileTabCharacter
    - LineLength
    - JavadocMethod
    
jscpd:
  args: "--threshold 10"