---
java:
  disable:
    - HideUtilityClassConstructor
    - VisibilityModifier
    - DesignForExtension
    - FileTabCharacter
    - LineLength
    - JavadocMethod
    - MethodName
    
checkstyle:
  disable:
    - HideUtilityClassConstructor
    - VisibilityModifier
    - DesignForExtension
    - FileTabCharacter
    - LineLength
    - JavadocMethod
    - MethodName
    
stylelint:
  disable:
    - font-family-no-missing-generic-family-keyword
    
jscpd:
  args: "--threshold 10"