---
name: CI-Pipeline

on:
  push:
    branches:
      - main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          JAVA_FILE_NAME: checkstyle.xml
          JSCPD_CONFIG_FILE: jscpd-linter.jscpd.json
          FILTER_REGEX_EXCLUDE: 'Profiler_visualvm_2110/.*'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  check-properties:
    name: Check app.properties for prod profile
    needs: super-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if spring.profiles.active=dev is commented out
        run: |
          if grep -qE '^\s*(#|//)\s*s*spring.profiles.active\s*=\s*dev' src/main/resources/application.properties; then
            echo "spring.profiles.active=dev is commented out, passing..."
          else
            echo "Error: spring.profiles.active=dev is not commented out"
            exit 1
          fi

  wait-for-approval:
    name: Wait for approval
    needs: check-properties
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Pause for approval
        run: echo "Waiting for approval..."
        
  push-image:
    name: Push Docker image
    needs: wait-for-approval
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/noteplan:latest
          docker build -t $IMAGE_NAME .
          echo "Built $IMAGE_NAME"

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/noteplan:latest
          docker push $IMAGE_NAME
