name: Build and Push Docker Image to GHCR

on:
  workflow_run:
    workflows: ["spring-linter.yml"]
    types:
      - completed

jobs:
  push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/noteplan:latest
          docker build -t $IMAGE_NAME .
          echo "Built $IMAGE_NAME"

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/noteplan:latest
          docker push $IMAGE_NAME
