---
name: Spring-Linter

on:
  push:
    branches:
      - main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          JAVA_FILE_NAME: checkstyle.xml
          JSCPD_CONFIG_FILE: jscpd-linter.jscpd.json
          FILTER_REGEX_EXCLUDE: 'Profiler_visualvm_2110/.*'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  approval:
    needs: super-lint
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Pause for approval
        run: echo "Waiting for approval..."
